[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
path = "src/main.rs"
name = "blog"

[dependencies]
actix-web = "4.0.0-rc.2"
serde = "1.0.132"
tracing = { version = "0.1.30", features = ["log"] }
tracing-log = "0.1.2"
tracing-actix-web = "0.5.0-rc.3"
tracing-subscriber = { version = "0.3.8", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
uuid = { version = "0.8.2", features = ["v4"] }
secrecy = { version = "0.8", features = ["serde"] }
sqlx = { version = "0.5.10", features = ["postgres", "chrono", "runtime-actix-rustls"] }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"

[dev-dependencies]
reqwest = { version = "0.11.9", features = ["json"]}
tokio = { version = "1.16.1", features = ["macros"]}
once_cell = "1.9.0"
