[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.18"
uuid = { version = "0.8.2", features = ["serde", "v4"]}
serde = "1.0.132"
serde_json = "1.0.73"
sqlx = { version = "0.5.10", features = ["postgres", "uuid", "chrono", "runtime-actix-rustls"] }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
